version: '3'
services:

  gateway:
    build:
      args:
        COMPONENT: gateway
    ports:
      - '8000:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTS_HOST=host.docker.internal:8001
      - THREADS_HOST=host.docker.internal:8002
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true

  posts:
    build:
      args:
        COMPONENT: posts
    ports:
      - '8001:8001'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTS_DSN=postgres://postgres:postgrespassword@host.docker.internal:7432?sslmode=disable
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true

  threads:
    build:
      args:
        COMPONENT: threads
    ports:
      - '8002:8002'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - THREADS_DSN=postgres://postgres:postgrespassword@host.docker.internal:8432?sslmode=disable
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true

  jaeger:
    # https://www.jaegertracing.io/docs/latest/getting-started/
    image: jaegertracing/all-in-one:latest
    environment:
      - LOG_LEVEL=error # default is rather chatty
    ports:
      - '16686:16686' # UI
      - '4317:4317' # OTLP over gRPC
      - '4318:4318' # OTLP over HTTP
