version: '3'
services:
  gateway:
    build:
      args:
        COMPONENT: gateway
    ports:
      - '8000:8000'
    network_mode: host
  posts:
    build:
      args:
        COMPONENT: posts
    ports:
      - '8001:8001'
    network_mode: host
  threads:
    build:
      args:
        COMPONENT: threads
    ports:
      - '8002:8002'
    network_mode: host
